title: Turtles All The Way Down
description: Words arranged in patterns

url: "http://www.vanbever.me/"
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about

social:
   github: frankvanbever
   twitter: fvbever
   email: frank.vanbever@gmail.com

