title: Turtles All The Way Down 
description: Words arranged in patterns 

url: "http://127.0.0.1:4000/"
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.html
 - title: Contact
   url: /contact.html

social:
   github: frankvanbever 
   twitter: fvbever 
   email: frank.vanbever@gmail.com

