baseURL = 'http://example.org/'
languageCode = 'en-us'
title = '/home/fvb'

theme = "fvb-theme"

[params]
    mainSections = ['posts']

[menu]
  [[menu.main]]
    name = "Posts"
    pre = "posts"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    pre = "about"
    url = "/about/"
    weight = 2

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'solarized-dark'
    tabWidth = 4