baseURL = 'http://example.org/'
languageCode = 'en-us'
title = '/home/fvb'

theme = "fvb-theme"

[params]
    mainSections = ['posts']

[menu]
  [[menu.main]]
    name = "Posts"
    pre = "posts"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    pre = "about"
    url = "/about/"
    weight = 2

