#+TITLE: FFT in C
#+DATE: 2023-12-29T18:48:54+01:00
#+DRAFT: true

Lately I've been doing a deep dive into DSP because I wanted to know how certain
audio effects work. I started off with a book about programming VST plugins,
however I found that the DSP course I took at university was a bit too long ago,
so I had to go back to basics.

# more

I worked my way through Julius O. Smith III's /Mathematics of the Discrete
Fourier Transform (DFT) With Audio Applications/ and it was a super interesting
experience, though also a lot of work. In the end I feel that I have a good
grasp on the Fourier transform and a lot of the mathematics underpinning it.

After having finished I figured that I should probably try to translate this
knowledge into something practical, so I decided that I wanted to implement the
DFT and Cooley-Tukey FFT in C.

Up until this point I've been exclusively working in Python, using Numpy, Scipy
and Matplotlib in a Jupyter Lab. The combination of these project makes
scientific computing a breeze.

Moving to C made me realize I never really have done something like this in my
15 years of experience. I have no clue how ~complex numbers~ work in C for
example. So these are my somewhat cleaned up notes of my process of figuring out
how to implement the DFT/FFT in C.

* Complex numbers

Complex numbers in C were introduced in the C99 standard. Everything you need is
available in ~complex.h~. In theory it's possible with some compiler magic to
get these things without the header (e.g. ~_Complex~ is seemingly available
without including the header) but it doesn't make a lot of sense to do that.

#+begin_src c
#include <complex.h>
#+end_src


A complex number is made up of a real and imaginary part. A declaration of a
complex number looks like this:

#+begin_src c
  double complex foo = 1.0 + 2.0*I;
#+end_src

This is a double precision floating point type. I is the imaginary constant. If
you want to get the separate real and imaginary part the functions ~creal~ and
~cimag~ provide these.

The following function does a pretty print of a complex number:

#+begin_src c
  #include <stdio.h>
  void print_complex(complex z)
  {
      printf("%f+%f*i\n", creal(z), cimag(z));
  }
#+end_src

Arithmetic works just like it would with regular types:

#+begin_src c
  void complex_arithmetic(void)
  {
      double complex a = 1.0 + 2.0*I;
      double complex b = 2.0 + 3.0*I;

      print_complex(a+b);
      print_complex(a-b);
      print_complex(a*b);
      print_complex(a/b);
  }
#+end_src

Gives the following output:

#+begin_src
3.000000+5.000000*i
-1.000000+-1.000000*i
-4.000000+7.000000*i
0.615385+0.076923*i
#+end_src

Which looks OK. This is really all we need to implement a DFT.


* Discrete Fourier Transform

The discrete Fourier transform is defined by the following formula

$$
X_{k} = \sum_{n = 0}^{N - 1} x_{n} \cdot e^{-\frac{i2\pi}{N}kn}
$$

We've got arithmetic down, but there's a couple more things that we need. First
of all there's the exponential function. Regularly you'd use ~exp( douple arg)~
as defined in ~math.h~. However, given that we're dealing with complex numbers
here we need the complex variant ~cexp(double complex z)~ instead. The other
thing is \(\pi\), which is defined as ~M_PI~ as part of the mathematical
constants that GCC adds to ~math.h~.

This gives us the following C implementation:

#+begin_src c
void dft(double complex *x, double complex *X, size_t len)
{
		int N = len;
		for (int k = 0; k < len; k++) {
				for (int n = 0; n < len; n++) {
						X[k] += x[n] * cexp(-1 * ((I*2*M_PI)/N) * k * n);
				}
		}
}
#+end_src

When we use the following loop to fill in some dummy sample data

#+begin_src c
		for (int i = 0; i < num_samples; i++) {
				x[i] = 1.0*i + 1.0*i*I;
		}
#+end_src

We get the following output:

#+begin_src
45.000000+45.000000*i
-20.388418+10.388418*i
-11.881910+1.881910*i
-8.632713+-1.367287*i
-6.624598+-3.375402*i
-5.000000+-5.000000*i
-3.375402+-6.624598*i
-1.367287+-8.632713*i
1.881910+-11.881910*i
10.388418+-20.388418*i
#+end_src

Let's compare if this output is correct by checking it against the ~numpy~ FFT
implementation.

#+begin_src python
  x = []
  for i in range(10):
      x.append(1.0*i + 1.0*i*1j)

  print(fft(x))
#+end_src

Let's compare the output of this with the output of our C function:

#+ATTR_HTML: :class table table-striped
| C                      | Python                                  |
|------------------------+-----------------------------------------|
| 45.000000+45.000000*i  | 45+45j                                  |
| -20.388418+10.388418*i | -20.388417685876266+10.388417685876266j |
| -11.881910+1.881910*i  | -11.881909602355867+1.8819096023558668j |
| -8.632713-1.367287*i   | -8.632712640026803-1.3672873599731972j  |
| -6.624598-3.375402*i   | -6.624598481164532-3.375401518835468j   |
| -5.000000-5.000000*i   | -4.999999999999998-5.000000000000002j   |
| -3.375402-6.624598*i   | -3.375401518835468-6.624598481164532j   |
| -1.367287-8.632713*i   | -1.3672873599731958-8.632712640026805j  |
| 1.881910-11.881910*i   | 1.8819096023558668-11.881909602355867j  |
| 10.388418-20.388418*i  | 10.388417685876263-20.388417685876263j  |

Those numbers look almost the same, the small differences can be attributed to
floating point rounding errors.

* COMMENT Cooley-Tukey FFT

The Cooley-Tukey FFT is an algorithm to compute the Fourier Transform faster
than the regular DFT. It's recursive in nature. The [[https://en.wikipedia.org/wiki/Cooley–Tukey_FFT_algorithm][Wikipedia article]] about it
is pretty good so I'd direct you over there for the explanation.

#+begin_src c
  int fft(complex double *x, size_t len, complex double **X)
  {
      int ret = -1;
      complex double *x_even = NULL;
      complex double *x_odd = NULL;

      complex double *X_even = NULL;
      complex double *X_odd = NULL;

      complex double *factor = NULL;

      ,*X = malloc(len * sizeof(complex double));
      if (*X == NULL) {
          goto cleanup;
      }

      if (len == 1) {
          (*X)[0] = x[0];
          return 0;
      } else {
          if (get_even(x, len, &x_even)) {
              goto cleanup;
          }
          if (get_odd(x, len, &x_odd)) {
              goto cleanup;
          }

          if (fft(x_even, len / 2, &X_even)) {
              goto cleanup;
          }

          if (fft(x_odd, len / 2, &X_odd)) {
              goto cleanup;
          }

          if (get_factor(len, &factor)) {
              goto cleanup;
          }

          for (int i = 0; i < len; i++) {
              int index = i % (len / 2);
              (*X)[i] = X_even[index] + X_odd[index] * factor[i];
          }
      }

      ret = 0;

  cleanup:
      if (x_even)
          free(x_even);
      if (x_odd)
          free(x_odd);
      if (X_even)
          free(X_even);
      if (X_odd)
          free(X_odd);
      if (factor)
          free(factor);

      return ret;
  }
#+end_src

The algorithm works recursively on the even and odd samples. To respectively get
the even and odd samples I use the following:

#+begin_src c
static int get_even(complex double *x, size_t len, complex double **even)
{
	size_t N = (len / 2) + (len % 2);

	*even = malloc(N * sizeof(complex double));
	if (*even == NULL) {
		return -1;
	}

	for (int i = 0; i < N; i++) {
		(*even)[i] = x[i * 2];
	}

	return 0;
}

static int get_odd(complex double *x, size_t len, complex double **odd)
{
	size_t N = len / 2;

	*odd = malloc(N * sizeof(complex double));
	if (*odd == NULL) {
		return -1;
	}

	for (int i = 0; i < N; i++) {
		(*odd)[i] = x[(i * 2) + 1];
	}

	return 0;
}
#+end_src

Using it on the same data that We've been using before gives the following results:

#+begin_comment
TODO add test data here
#+end_comment

which as you can see corresponds pretty well with what we got from both Python
and the DFT. There's some shenanigans happening with positive and negative zero
but I'm chalking that up to ~IEEE 754~ being weird.
